# Copyright (C) 2026 Leif Barton
# Licensed under the Open Software License 3.0

name = "backend"
main = "build/index.js"
compatibility_date = "2026-06-02"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[env.prod.vars]
ENVENV="prod"

[[env.prod.d1_databases]]
binding="DB"
database_name="bbcr"
database_id="03f490ed-bd15-4d0c-ab2b-f25ef7bc895b"
remote=true


[env.dev.vars]
ENVENV="dev"

[[env.dev.d1_databases]]
binding="DB"
database_name="bbcr"
database_id="03f490ed-bd15-4d0c-ab2b-f25ef7bc895b"
remote=true


[[routes]]
pattern="api.bot.leifbarton.dev"
custom_domain=true